# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - checkout: self
  - script: |
      echo "##vso[task.setvariable variable=COMMIT_ID]$(git rev-parse --short=3 HEAD)"
    displayName: 'Get Short Commit ID'
  - script: |
      echo "##vso[build.updatebuildnumber]$(Build.BuildNumber)-$(COMMIT_ID)"
    displayName: 'Set Build Number'
  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.Repository.Name):$(Build.BuildNumber)
  - task: Docker@2
    inputs:
      command: 'push'
      tags: |
        $(Build.Repository.Name):$(Build.BuildNumber)
